// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYPOdXXEY130bLNnXaK3FqhsST5v8waA',
    appId: '1:414640959803:web:4773a44ef79a95b1f0471e',
    messagingSenderId: '414640959803',
    projectId: 'alert-95771',
    authDomain: 'alert-95771.firebaseapp.com',
    databaseURL: 'https://alert-95771-default-rtdb.firebaseio.com',
    storageBucket: 'alert-95771.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgza5kWDi3qY9QbHhd5S7rtOwwSowHBd8',
    appId: '1:414640959803:android:4e5029fea395292ef0471e',
    messagingSenderId: '414640959803',
    projectId: 'alert-95771',
    databaseURL: 'https://alert-95771-default-rtdb.firebaseio.com',
    storageBucket: 'alert-95771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1XnI9GrB6bxLTkGy5uLl0oD71Ct5gs4k',
    appId: '1:414640959803:ios:449243e61c0efe1af0471e',
    messagingSenderId: '414640959803',
    projectId: 'alert-95771',
    databaseURL: 'https://alert-95771-default-rtdb.firebaseio.com',
    storageBucket: 'alert-95771.firebasestorage.app',
    iosBundleId: 'com.phone.alertmecel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1XnI9GrB6bxLTkGy5uLl0oD71Ct5gs4k',
    appId: '1:414640959803:ios:449243e61c0efe1af0471e',
    messagingSenderId: '414640959803',
    projectId: 'alert-95771',
    databaseURL: 'https://alert-95771-default-rtdb.firebaseio.com',
    storageBucket: 'alert-95771.firebasestorage.app',
    iosBundleId: 'com.phone.alertmecel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrYPOdXXEY130bLNnXaK3FqhsST5v8waA',
    appId: '1:414640959803:web:62d975ac81a41347f0471e',
    messagingSenderId: '414640959803',
    projectId: 'alert-95771',
    authDomain: 'alert-95771.firebaseapp.com',
    databaseURL: 'https://alert-95771-default-rtdb.firebaseio.com',
    storageBucket: 'alert-95771.firebasestorage.app',
  );
}
